### ISSUE TITLE
Profile picture missing

### ISSUE THREAD

**Issue by cristijora** [creativetimofficial/light-bootstrap-dashboard-react#1]
The profile picture seems to be missing on User Profile page
![image](https://user-images.githubusercontent.com/15955045/30655334-45ad2fa4-9e39-11e7-876c-59d52ceb7e00.png)
![image](https://user-images.githubusercontent.com/15955045/30655340-4c8b1b6a-9e39-11e7-86c0-ac04c272f6ab.png)

**Comment by EINazare** [comment]
@cristijora thank you for your feedback. The light bootstrap dashboard react has two folders, src and public, the problem here is that the image points to public/assets/img, when it should point to src/assets/img. We have changed the product so that it points to src/assets/img.

Best,
    Manu
