### ISSUE TITLE
SweetAlert and Modal component issue

### ISSUE THREAD

**Issue by eduardoamills** [creativetimofficial/light-bootstrap-dashboard-react#11]
Hi,
I have some problems to integrate Sweet Alert or Modal component to the View with Jquery Datatables.

Here part of my code:

import React, {Component} from 'react';
// jQuery plugin - used for DataTables.net
import $ from 'jquery';
import {Grid, Row, Col} from 'react-bootstrap';

import Card from 'components/Card/Card.jsx';
import Button from 'elements/CustomButton/CustomButton.jsx';
import SweetAlert from 'react-bootstrap-sweetalert';
require('datatables.net-responsive');
$.DataTable = require('datatables.net-bs');

class Main extends Component {
  constructor(props){
      super(props);
      this.state = {
          alert: null
      };
  }
  warningWithConfirmMessage(){
      this.setState({
          alert: (
              <SweetAlert
                  warning
                  style={{display: "block",marginTop: "-100px"}}
                  title="Are you sure?"
                  onConfirm={() => this.successDelete()}
                  onCancel={() => this.hideAlert()}
                  confirmBtnBsStyle="info"
                  cancelBtnBsStyle="danger"
                  confirmBtnText="Sí, bórralo!"
                  cancelBtnText="Cancelar"
                  showCancel
              >
                  ¿Esta seguro de borrar el usuario?
              </SweetAlert>
          )
      });
  }
  successDelete(){
      this.setState({
          alert: (
              <SweetAlert
                  success
                  style={{display: "block",marginTop: "-100px"}}
                  title="Deleted!"
                  onConfirm={() => this.hideAlert()}
                  onCancel={() => this.hideAlert()}
                  confirmBtnBsStyle="info"
              >
                  Your imaginary file has been deleted.
              </SweetAlert>
          )
      });
  }
  hideAlert(){
      this.setState({
          alert: null
      });
  }
    return (<div className="main-content">
      <Grid fluid={true}>
        <Row>
          <Col md={12}>

            <Card title="Usuarios del sistema" content={<div className = "fresh-datatables" >
             <Button fill onClick={this.warningWithConfirmMessage.bind(this)}>Try me!</Button>

The main problem is that I dont get any errors, but the component is never showed..
in other parts of my project does not work either.

Can you help me??

regards

**Comment by sagarjayashankar** [comment]
I am also facing the same problem...
In my project, I have a datatable which has a delete icon. When the user clicks on the icon the sweetalert should show for confirmation.
The code is `{
            data: "id",
            title: "Action",
            render: id =>
             `<div>
               <a href="/dev/courier/edit/${id}">
                 <i class="fa fa-pencil" aria-hidden="true" style="color:black;"></i>
               </a>&nbsp;&nbsp;
                 <i class="fa fa-trash" aria-hidden="true" style="color:black;"  onclick=${() =>
                   this.setState({ show: true })}></i>
             </div>`
          }`
I have to set the state to show the alert message...

**Comment by EINazare** [comment]
Hello there, @sagarjayashankar ,

Thank you for your interest in working with our products.
Unfortunately, on our product, we do not make use of data tables.
Maybe you are on the wrong repository?

Best,
Manu
