### ISSUE TITLE
Is there support for RTL languages?

### ISSUE THREAD

**Issue by Mulli** [creativetimofficial/light-bootstrap-dashboard-react#12]
I could not find a simple way to RTL the display:
- Sidebar to the right
- Reverse order for table columns 
- etc...

**Comment by EINazare** [comment]
Hello @Mulli ,

Thank you for your interest in our product.
Yes, you can add RTL by following these steps:
1. Add in `public/index.html` file this line `<link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">` inside the `<head>...</head>` tags.
2. Replace `<body>` with `<body class="rtl-active">` inside the `public/index.html` file.
3. Download this file
[lbdp_rtl.scss.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-react/files/1743606/lbdp_rtl.scss.zip)
4. Unzip the file.
5. Add the unzipped file in `src/assets/sass/lbd/` folder.
6. Add this line `@import "lbd/lbdp_rtl";` at the end of the `src/assets/sass/light-bootstrap-dashboard.scss` file.

**Comment by Mulli** [comment]
Thanks.
I was able to RTL it myself but not as clean as suggested.
Will give it a try soon.

Do you see a way to trigger RTL using a config flag?
