### ISSUE TITLE
manifest Imported Twice

### ISSUE THREAD

**Issue by romarioraffington** [creativetimofficial/light-bootstrap-dashboard-react#15]
I see that the line `<link rel="manifest" href="%PUBLIC_URL%/manifest.json">` is imported twice in the `index.html`.

Can you explain, why this was imported twice? Thanks

**Comment by EINazare** [comment]
Hello @romarioraffington ,

Thank you for your interest in our product.
This is just a simple mistake, the first one should not be there, not really sure how it got there. On a few weeks we are going to update this products and we are going to delete the first import.

Thank's again for your notice.

Best,
Manu
