### ISSUE TITLE
Is chart.js used?

### ISSUE THREAD

**Issue by cristijora** [creativetimofficial/light-bootstrap-dashboard-react#2]
I see references to chart.js and react-chartjs-2
https://github.com/creativetimofficial/light-bootstrap-dashboard-react/blob/master/package.json#L6

It seems that the dashboard only uses chartist. 
Maybe clean dependencies which are not used.
This will improve installation time a bit.

**Comment by EINazare** [comment]
@cristijora thank you for your interest in out product. We have changed the dependencies in our product, deleted the unnecessary ones and kept only the ones that are used.

Best,
    Manu
