### ISSUE TITLE
Custom sidebar color

### ISSUE THREAD

**Issue by donalmurtagh** [creativetimofficial/light-bootstrap-dashboard-react#21]
According to the docs, this template

> comes with 6 filter colors for the sidebar (black, azure, green, orange, red, purple) and an option to have a background image.

In my case, I've removed the background image and now would like to change the background color of the sidebar to `#0b7c9c`.

I tried to achieve this by removing the `data-color` attribute from this element in `Sidebar.jsx`
```
<div id="sidebar" className="sidebar" data-color="black">
```
And adding a CSS rule
```
#sidebar {
  background-color: #0b7c9c;
}
```
But the sidebar still has a black background color. How can I change the background color of the sidebar to `#0b7c9c`?

**Comment by EINazare** [comment]
Hello @donalmurtagh ,

Thank you for your interest in using our products.
The color on the sidebar comes from the `:after` property in scss.
It is not directly on the div.
If you haven't made any changes to our scss, than navigate in your project in `src/assets/sass/lbd/_sidebar-and-main-panel.scss`, and at line and between lines 217 and 234 you will find this code:
```
&[data-color="blue"]:after{
        @include icon-gradient($new-dark-blue, $blue-color-bottom);
    }
    &[data-color="azure"]:after{
        @include icon-gradient($new-blue, $azure-color-bottom);
    }
    &[data-color="green"]:after{
        @include icon-gradient($new-green, $green-color-bottom);
    }
    &[data-color="orange"]:after{
        @include icon-gradient($new-orange, $orange-color-bottom);
    }
    &[data-color="red"]:after{
        @include icon-gradient($new-red, $red-color-bottom);
    }
    &[data-color="purple"]:after{
        @include icon-gradient($new-purple, $purple-color-bottom);
    }
```
And this is how we've put that background color. You can either change one of these, and ad your custom background color on it, or you can add your own custom color, something like:
```
    &[data-color="custom-blue"]:after{
        background: #0b7c9c;
    }
```
And than in the sidebar component put the data color to `custom-blue`.

Hope that information helps you. Please let us know if we can help you with anything else.

Best,
Manu

**Comment by donalmurtagh** [comment]
Thanks a lot for your help
