### ISSUE TITLE
Tuts needed for the LBD Pro React

### ISSUE THREAD

**Issue by joshueoconnor** [creativetimofficial/light-bootstrap-dashboard-react#23]
I like this admin theme and think it could be really useful but I'm a little disappointed in that the lack of 'how to' get started etc. If there were some video tuts for this (and not just the LDB theme) it would be great. Also a simple 'how to' step by step blog post or something would be good.

**Comment by joshueoconnor** [comment]
Also - its not clear if you should create a new admin theme from scratch or hack the existing one etc, for example..

**Comment by EINazare** [comment]
Hello @joshueoconnor ,

Thank you for your interest in our product.
[Isn't our documentation enough for a "getting started" tutorial](https://demos.creative-tim.com/light-bootstrap-dashboard-react/?_ga=2.183000037.233054020.1527576442-329288944.1519374311#/documentation/getting-started)?
The "how to" it's actually the whole project, you take the project, and start messing with it using the components shown in it. I think it is quite intuitive on "how to" use it and does not require a tutorial on "how to".

Best,
Manu

**Comment by joshueoconnor** [comment]
Wow - ok! Tbh, I find the current documentation very light, beyond being a useful reference. Nevermind.
