### ISSUE TITLE
How to create new customised Dashboards for different flows?

### ISSUE THREAD

**Issue by joshueoconnor** [creativetimofficial/light-bootstrap-dashboard-react#25]
I want to create different dashboards depending on user type. How do I do this?

Thanks

Josh

**Comment by EINazare** [comment]
Hello again @joshueoconnor ,

I think this kind of a specific question which you should figure yourself out.
I mean that there are multiple ways to achieve what you are asking for, for example you could make some specific routes `dashboard\1\...`,  `dashboard\2\...` and so on, you get the idea. An depending on the route, if it is `\1\`, than you render the number 1 dashboard, and so on.
But once again, there are multiple ways, and quite frankly we do not offer support for this.
If you have further information about this i am not sure i will be able to help you, but maybe the community will.

Best,
Manu
