### ISSUE TITLE
Small bug with mobileSidebarToggle

### ISSUE THREAD

**Issue by Jin-Zheng** [creativetimofficial/light-bootstrap-dashboard-react#27]
As I understand, when `mobileSidebar` is toggled on, an element `bodyClick` is created which will toggle `mobileSidebar` again on click.

When clicking on a sidebar view (ex. navigating from Dashboard to User Profile in the demo), the `mobileSidebar` is toggled again but without removing the `bodyClick` element, meaning that the first click of the page will toggle on the `mobileSidebar` again, leaving the `mobileSidebar` constantly toggled in the opposite position we want.

A quick fix I made for this is placing this code:
`
                var d = document.getElementById("bodyClick");
                if (d)
                    d.parentElement.removeChild(d);`
In Sidebar.jsx when the NavLinks are being placed.

**Comment by EINazare** [comment]
Hello @Jin-Zheng ,

Thank you for your interest in suing our products and for telling us about this.
We are going to fix it in our next update.

Best,
Manu

**Comment by hamza-ghufran** [comment]
In Header.jsx replace the 'mobileSidebarToggle'  function with : 

mobileSidebarToggle (e) {
    e.preventDefault();  
    document.documentElement.classList.toggle('nav-open');
    
    var bodyClick = document.getElementById("bodyClick");
    if (bodyClick) {
      bodyClick.parentElement.removeChild(bodyClick);
    } else {
      var node = document.createElement('div');
      node.id = 'bodyClick';
      document.body.appendChild(node);
      node.onclick = () => {
       document.documentElement.classList.toggle('nav-open');
        
      var bodyClick = document.getElementById("bodyClick");
      bodyClick.parentElement.removeChild(bodyClick); 
      }
    }
  }
