### ISSUE TITLE
Documentation for adding light-bootstrap-dashboard-react into existing react project

### ISSUE THREAD

**Issue by noumanDev** [creativetimofficial/light-bootstrap-dashboard-react#28]
hello
Is there any documentation for adding light-bootstrap-dashboard-react into existing react project

**Comment by EINazare** [comment]
Hello @noumanDev ,

As of moment there is no docs for this, but it should be fairly easy to do so.
You only need to install our dependencies, copy our css or scss intro your project and after that just copy paste our components.

Best,
Manu
