### ISSUE TITLE
Add new layout to index.jsx

### ISSUE THREAD

**Issue by nimesha95** [creativetimofficial/light-bootstrap-dashboard-react#30]
Hi, 
I've tried to add my own component into this application.

**What i've done:**
added my component into the indexRoutes, my indexRoutes looks like below,

`var indexRoutes = [
    { path: "/testing", name: "testing", component: Testing },
    { path: "/", name: "Home", component: Dashboard },
];`

**Result:**
It only renders one route, in my case, "/testing" route. What am i doing wrong?
Thanks

**Comment by EINazare** [comment]
Hello there @nimesha95 ,

And thank you for your interest in using our product.
The problem comes from `src/index.js`.
Please change
```
return <Route to={prop.path} component={prop.component} key={key} />;
```
to
```
return <Route path={prop.path} component={prop.component} key={key} />;
```

Best,
Manu

**Comment by miteshnath** [comment]
Hello 

I also faced the same issue. I have changed the 'to' prop to 'path' but this raises a issue that dashboard redirects like to '/user' or '/icons' don't work anymore

I need a '/login' page which takes me to Login page and a '/dashboard' route for taking to dashboard page and then also from dashboard sidebar I need to go to pages like '/user', '/icons', etc.

**Comment by miteshnath** [comment]
Hi @nimesha95 @EINazare Any help would be appreciated!

**Comment by nimesha95** [comment]
Oh.. sorry i don't think i'll be able to help you in this matter. I also faced the same issues and decided to rather dan use react template, use the html one instead and use my own defined routes

**Comment by EINazare** [comment]
Hello there @miteshnath ,

Thank you for your interest in working with our products.
Right now I have some critical issues to attend to and I can't help you.
I am going to do my best to take a look at your issue next week. 
I hope you can understand me.
Once again, really sorry about this.

Best,
Manu
