### ISSUE TITLE
Having trouble with FormInputs

### ISSUE THREAD

**Issue by jedusaad** [creativetimofficial/light-bootstrap-dashboard-react#33]
Im new to react, and i downloaded the free theme. Everywhere i search,  its says that you handle forms with a onChange on the component, and a handleChange function. But i can't seem to make it work with your FormInput component. Sorry for the newbie question, but i've really spent some time searching and found no help so far.
Thanks !

**Comment by EINazare** [comment]
Hello there @jedusaad ,

Thank you for your interest in working with our product.
Here is a sample code for solving your problem:
```
import React from "react";

import { FormInputs } from "components/FormInputs/FormInputs.jsx";

class Example extends React.Component {
  handleChange() {
    console.log("Hey");
  }
  render() {
    return (
      <FormInputs
        ncols={["col-md-5"]}
        proprieties={[
          {
            label: "Username",
            type: "text",
            bsClass: "form-control",
            placeholder: "Username",
            defaultValue: "michael23",
            onChange: this.handleChange
          }
        ]}
      />

    );
  }
}

export default Example;
```

Best,
Manu

**Comment by jedusaad** [comment]
Hello! 
Sure, this works. But everytime i try something like
`  handleChange(e){
    console.log("handleChange", e.target.value);
    this.setState({ myVar : e.target.value });
  }`

I get the following error, 

TypeError: Cannot read property 'setState' of undefined

Thanks anyway!

**Comment by EINazare** [comment]
Hello again @jedusaad ,

That is because `this` is not bind to your function. The `handleChange` function does not have access to `this` of the class in which it was declared.
[Read here](https://reactjs.org/docs/faq-functions.html#how-do-i-bind-a-function-to-a-component-instance) more about your problem.

Best,
Manu

**Comment by jedusaad** [comment]
The thing is, i had it declared at my constructor. Thanks anyway!
