### ISSUE TITLE
cannot load CSS files when using webpack

### ISSUE THREAD

**Issue by avinashshetty** [creativetimofficial/light-bootstrap-dashboard-react#36]
Hello, 
I think the CSS files provided only work with create-react-app ONLY. I am using webpack to bundle the client code separately. CSS files I use gets loaded and no errors but when I use your dashboard template none of the CSS gets loaded. example error as below 
ERROR in ./client/assets/sass/light-bootstrap-dashboard.css?v=1.2.0
Module parse failed: Unexpected character '@' (18:0)
You may need an appropriate loader to handle this file type.
|  */
| /*      light colors         */
| @keyframes spin {
|   from {
|     transform: rotate(0deg); }
 @ ./client/MainRouter.js 23:0-62

All these lines fail
import "./assets/css/animate.min.css";
import "./assets/sass/light-bootstrap-dashboard.css?v=1.2.0";
import "./assets/css/demo.css";
import "./assets/css/pe-icon-7-stroke.css";

I am sure there is a way to make it work in webpack. Can you please help me correct this for me please?

My current Webpack config file is
const path = require('path')
const webpack = require('webpack')
const CURRENT_WORKING_DIR = process.cwd()

const config = {
    name: "browser",
    mode: "development",
    devtool: 'eval-source-map',
    entry: [
        'react-hot-loader/patch',
        'webpack-hot-middleware/client?reload=true',
        path.join(CURRENT_WORKING_DIR, 'client/main.js')
    ],
    output: {
        path: path.join(CURRENT_WORKING_DIR , '/dist'),
        filename: 'bundle.js',
        publicPath: '/dist/'
    },
    module: {
        rules: [
            {
                test: /\.js?$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: "babel-loader",
                        options: { presets: ["es2015", "react", "stage-2"] }
                    }
                ]
            },
            {
                test: /\.scss$/,
                use: [
                    {   loader: "style-loader"}, // creates style nodes from JS strings
                    {   loader: "css-loader"  }, // translates CSS into CommonJS
                    {   loader: "sass-loader" } // compiles Sass to CSS
                ]
            },
            {
                test: /\.(ttf|eot|svg|gif|jpg|png|css)(\?[\s\S]+)?$/,
                use: [
                    { loader: "style-loader" }, // creates style nodes from JS strings
                    { loader: "css-loader" }, // translates CSS into CommonJS
                    { loader: "sass-loader" }, // compiles Sass to CSS
                    { loader: "file-loader"}
                ]
            }
        ]
    },  
    plugins: [
          new webpack.HotModuleReplacementPlugin(),
          new webpack.NoEmitOnErrorsPlugin()
      ]
}

module.exports = config

**Comment by EINazare** [comment]
Hello there @avinashshetty ,

Thank you for your interest in working with our products.
Here are some of our tutorials on how to work with Webpack - please note that the error above does not come from our product, is an issue with your webpack config, and after following the instructions on the tutorials you will understand:

- [YouTube tutorial](https://youtu.be/no2PD2kq-dE)
- [Medium post](https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618)

Best,
Manu
