### ISSUE TITLE
Module not found:  attempting to import which falls outside of the project src

### ISSUE THREAD

**Issue by Tondy** [creativetimofficial/light-bootstrap-dashboard-react#37]
Hello

So after cloning the light bootstrap dashboard react I ran npm install. Then wehn trying to run npm start I recieve the error below but the imported script is with in the src folder. Please help.

Module not found: You attempted to import /layouts/Dashboard/Dashboard.jsx which falls outside of the project src/ directory. Relative imports outside of src/ are not supp
orted. You can either move it inside src/, or add a symlink to it from project's node_modules/.

**Comment by EINazare** [comment]
Hello there @Tondy ,

Thank you for your interest in working with our products.
When I clone this repo, give it a `npm install && npm start`, it doesn't give me any errors. 
What changes have you done to it?
Could you please give me a step by step reproduction?

Best,
Manu

**Comment by Tondy** [comment]
Hello ELNazare

So I went through the process of unzipping the file and running npm install and npm start .

This is the error I receive

Failed to compile.

./src/index.js
Module not found: Can't resolve 'routes/index.jsx' in 'C:\Users\pc\Desktop\avi\Dashadmin\src'

This is without making any changes. Hope you can help.

**Comment by EINazare** [comment]
Hello again @Tondy ,

Is this thread helpful to you: https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/4 ?

Best,
Manu

**Comment by Tondy** [comment]
Hi Manu

From the tagged instruction at #4 . I did the following steps.

Change NODE_PATH=src to NODE_PATH=./src inside .env file
Change react-scripts start to cross-env NODE_PATH=./src react-scripts start inside package.json

But this error keeps appearing 

Failed to compile.
./src/index.js
Module not found: Can't resolve 'routes/index.jsx' in 'C:\Users\pc\Desktop\avi\Dashadmin\src'

I also seem not to be able to locate the app.js code. 

Hope you can help.

**Comment by Tondy** [comment]
Hi Manu

Thank you very much it works.
