### ISSUE TITLE
Failed to compile after install

### ISSUE THREAD

**Issue by cesoftinfo** [creativetimofficial/light-bootstrap-dashboard-react#4]
Can't start app?
./src/index.js
Module not found: Can't resolve 'containers/App/App.jsx'

**Comment by EINazare** [comment]
Hi @cesoftinfo . Can you verify if you have downloaded the whole project and if you have the `App.jsx` file in `src/containers/App` subfolder? If you have this file, than a problem that i can think of, is that the import line of App.jsx is wrong. You can change line 10 in `src/index.js` `import App from 'containers/App/App.jsx';` with  `import App from './containers/App/App.jsx';` or with something similar. My guess is that it doesn't have the correct path to `App.jsx`.

**Comment by Arqu** [comment]
Have the same issue. I'm running on MacOS X Sierra and npm 5.4.2 with node 8.2.1. Changed the path for App to be relative, then variables from the App.jsx throw, adding `../../` there solves the issue, however more pop up. Seems like the relative paths need to be set up instead of absolute.

**Comment by yingkeen** [comment]
@Arqu thank you for the temp fix.

**Comment by cristijora** [comment]
@Arqu @yingkeen I would recommend against such edits inside node_modules since they will be overridden once you install the project on another pc (a teammate wants to setup the project) or for some reason you delete node_modules. 

I would rather try one of the following things
1. Change `NODE_PATH=src` to `NODE_PATH=./src` inside `.env` file
2. Change `react-scripts start` to `cross-env NODE_PATH=./src react-scripts start` inside package.json

The second option would require [cross-env](https://www.npmjs.com/package/cross-env) to be installed globally

**Comment by Arqu** [comment]
Agree completely, thats why this was a temporary workaround just to get it going. Thanks for showing the proper way do it still getting a grasp of react.

**Comment by maverickdude** [comment]
@cristijora Thank you so much. I tried with .env and it worked.
I'm too grasping the concepts of react and JS world.

**Comment by cesoftinfo** [comment]
Installing cross-env and changing react-scripts start to cross-env NODE_PATH=./src react-scripts start inside package.json workerd for me.Thanks.

**Comment by jlbooker** [comment]
Had this same problem too when using the .zip bundle download. I deleted the files from the .zip release, then cloned the project from GitHub and everything seems to work.

It looks like the .env file is not included in the .zip bundle, but is included in the repo.

**Comment by faisy26** [comment]
i also have same problem and i try all solution but it did'nt work
can anyone tell?
problem:  Failed to compile
./src/index.js
Module not found: Can't resolve 'assets/css/argon-dashboard-react.css' in 'F:\SKILLS\React\project\src'
This error occurred during the build time and cannot be dismissed.

**Comment by EINazare** [comment]
> i also have same problem and i try all solution but it did'nt work
> can anyone tell?
> problem: Failed to compile
> ./src/index.js
> Module not found: Can't resolve 'assets/css/argon-dashboard-react.css' in 'F:\SKILLS\React\project\src'
> This error occurred during the build time and cannot be dismissed.

Hello there, @faisy26 ,

Your error says `argon-dashboard-react`.
We are on the Light Bootstrap Dashboard React product.
Could you please provide us with the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* [If on Mac, Linux or Ubuntu Systems] Run npm run install:clean
* [If on Windows Systems] Run npm install
* [If on Windows Systems] Run npm start
* Showcase the issue

Best,
Manu
