### ISSUE TITLE
how can i change css styles? plzzzz urgent!!!!

### ISSUE THREAD

**Issue by squirtle34** [creativetimofficial/light-bootstrap-dashboard-react#42]
When i edit the "light-bootstrap-dashboard.css" file and i close my prompt window, and build again the project, the css styles who i change returns to its original state... how can i change it????

Sorry for my english.

**Comment by EINazare** [comment]
Hello there @squirtle34 ,

Thank you for your interest in working with our products.
That is because the css is auto-compiled from the scss.
If necessary change the scss files, or, create your own css file and import it inside your app.

Best,
Manu
