### ISSUE TITLE
How to change sidebar background image

### ISSUE THREAD

**Issue by bumbumpaw07** [creativetimofficial/light-bootstrap-dashboard-react#43]
I try changing copy of default sidebar background, but no background image is shown.

**Comment by EINazare** [comment]
Hello there @bumbumpaw07 ,

Thank you for your interest in working with our products.
The css is auto-compiled from the scss files located inside `src/assets/scss`.
If you want to modify our styles you should change those files, but we do not recommend this.
We recommend you to create your own style files, either scss or css.

Best,
Manu
