### ISSUE TITLE
Consider adding backend hooks

### ISSUE THREAD

**Issue by bnazaruk** [creativetimofficial/light-bootstrap-dashboard-react#44]
It's really confusing how real backend routing is abstracted from us and the first router we see includes the ui right away.

There's no space to add an actual backend logic/listeners on the same port.

**Comment by EINazare** [comment]
Hello there @bnazaruk ,

Thank you for your interest in working with our products.
Can you please detail?
Since I've only worked on front-end, I do not understand the issue.

Best,
Manu

**Comment by bnazaruk** [comment]
Well, the repo is literally not usable without integration with some kind of backend logic. I find it really hard to make use of the Node app that this repo runs. 

For now, the most feasible solution I found is via a reverse proxy that would redirect all requests to, say, :3000/api to :8080/api before React's router kicks in and spoils everything. Sure, I could make the app to connect to :8080 directly, but it causes origin conflicts. Still, the proxy solution is more of a hack, I shouldn't need a reversed proxy just to run my app.

I've tried using proxy in the package.json like ` "proxy": "http://localhost:8080"` But haven't been successful as of yet. Will try more. I'm also thinking about installing some additional npm modules that would override sloppy React's routing and give me some space to breathe there.

**Comment by EINazare** [comment]
Hello again, @bnazaruk ,

I am sorry about this issue.
To be honest, I don't quite follow your comments.
I am sure that any React app that has back-end logic can be added to this product, actually to any of our products.
By the end of May, we are going to release a tutorial on how to integrate one of our products with Firebase (which from my knowledge is a back-end), and we are also going to release a tutorial on how to integrate one of our products with an API (timeline for this is not set yet).
In the meantime, you can see our tutorials here:

1. 
 - https://medium.freecodecamp.org/how-to-use-redux-in-reactjs-with-real-life-examples-687ab4441b85
- https://www.youtube.com/watch?v=raKV5Rb8oOM&list=PLWxSJr7LCl87rGlQtTo2PoX8hboUU0R8a

2.
 - https://medium.freecodecamp.org/how-to-use-reactjs-with-webpack-4-babel-7-and-material-design-ff754586f618
 - https://www.youtube.com/watch?v=no2PD2kq-dE&list=PLWxSJr7LCl87OomktWFQVW30QDWtBqFlx

Also, if you're having problems with your development, we can recommend you some friends, but for that, you need to open a ticket on [our contact-us form](https://www.creative-tim.com/contact-us) and choose "I want to hire you..".

Hope this helps.

Best,
Manu
