### ISSUE TITLE
Sub-menu sidebar 

### ISSUE THREAD

**Issue by jdk1997** [creativetimofficial/light-bootstrap-dashboard-react#46]
How to add sub menus in the sidebar?

**Comment by EINazare** [comment]
Hello there @jdk1997 ,

Thank you for your interest in working with our products.
This is a PRO feature, and cannot be added in the FREE product. I am sorry about this.
Here is a link for the PRO product:
- [Buy link](https://www.creative-tim.com/product/light-bootstrap-dashboard-pro-react)
- [Live preview link](https://demos.creative-tim.com/light-bootstrap-dashboard-pro-react/#/dashboard)

Best,
Manu
