### ISSUE TITLE
[Bug] failure to start: Cannot find module '@csstools/normalize.css'

### ISSUE THREAD

**Issue by marcoeg** [creativetimofficial/light-bootstrap-dashboard-react#55]
### Version
1.3
### Reproduction link
https://www.creative-tim.com/new-issue/light-bootstrap-dashboard-react
### Operating System
linux Ubuntu 18.04
### Device
Dell XPS 15
### Browser & Version
Chrome 
### Steps to reproduce
clone the repo
$ npm install
$ npm start

### What is expected?
The browser to start
### What is actually happening?
Failed to compile.

./src/assets/css/pe-icon-7-stroke.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./src/assets/css/pe-icon-7-stroke.css)
Error: Cannot find module '@csstools/normalize.css'

---

**Comment by EINazare** [comment]
Hello there, @marcoeg ,

Thank you for your interest in working with our products and sorry for this late response.
I've tested and re-tested your issue, clone the repo, run install and start commands, and no errors where given.
Could you please make sure you have the latest LTS version of npm and NodeJS?
Also, if the error persists, I will require from you a video with the following:
- Download / Clone of the product
- Open Terminal
- Go inside the downloaded folder / cloned folder
- Run `ls` in the terminal - so I can make sure the folder you are in, is the correct one
- Open the package.json file from the terminal - once again, so I can make sure you are in the correct folder / the folder that was just downloaded/cloned
- Run npm install
- Run npm start
- Showcase the error

Best,
Manu
