### ISSUE TITLE
 Check the render method of `Header`.

### ISSUE THREAD

**Issue by ssusko** [creativetimofficial/light-bootstrap-dashboard-react#57]
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Header`. - not even sure where to find this - new to react

**Comment by EINazare** [comment]
Hello there, @ssusko ,

I've checked the product (Light Bootstrap Dashboard React), but I do not see any warnings.
Are you sure you are on the right product repository? 
Could you please use our issue template:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/light-bootstrap-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

Best,
Manu

**Comment by KevinFrazier** [comment]
I got this issue when I updated the react-bootstrap to v1.0.1 (as opposed to v0.32.4

**Comment by EINazare** [comment]
Hello there, @KevinFrazier ,

This product comes with Bootstrap 3, and not Bootstrap 4.
React-Bootstrap v1 is made to work with Bootstrap 4, and not Bootstrap 3 and this is why you are getting issues.
Please revert the changes.

Best,
Manu
