### ISSUE TITLE
[Bug] Visual glitches in the sidebar menu on small screens

### ISSUE THREAD

**Issue by bbstudio-dev** [creativetimofficial/light-bootstrap-dashboard-react#58]
### Version
1.3.0
### Reproduction link
https://demos.creative-tim.com/light-bootstrap-dashboard-react/#/admin/dashboard
### Operating System
OS X Mojave 10.14.15
### Device
MacBook Pro 2016
### Browser & Version
Chrome Version 76.0.3809.132 (Official Build) (64-bit)
### Steps to reproduce
1 Navigate to the official demo https://demos.creative-tim.com/light-bootstrap-dashboard-react/#/admin/dashboard
2. Start reducing the width of the window to trigger a responsive layout for small screens (alternatively, open Chrome Dev Tools, and activate a mobile device viewing ~ iPhone)
3. Click on the menu icon
4. Note that highlighting of Upgrade To Pro overlaps with Notifications as shown here http://prntscr.com/p9lnqm
(IMO the way this demo merges items from the top menu with the items from the sidebar does not look nice)
### What is expected?
No overlapping between UPGRADE TO PRO and NOTIFICATIONS
### What is actually happening?
Items overlap

---

**Comment by EINazare** [comment]
Hello there, @eps0001 ,

Thank you for your interest in working with our products.
That is actually expected behavior.
We will discuss this on our next meeting with the Creative Tim Board.

Best,
Manu
