### ISSUE TITLE
fail to start server

### ISSUE THREAD

**Issue by tramphbHQ2-GE07** [creativetimofficial/light-bootstrap-dashboard-react#59]
I using npm start to start server but always appear error: "Can't resolve 'layouts/Admin.jsx' in 'C:\Users\xxx\Documents\Project\react\src'"

**Comment by EINazare** [comment]
Hello there, @tramphbHQ2-GE07 ,

Why did you not follow our rules?
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/light-bootstrap-dashboard-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->

```
When I press the *New issue* button, I am prompted with the above comment.
Did that not open when you've pressed the *New issue* button?

Your issue can be solved by reading this thread here:
https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/4

Best,
Manu
