### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by guru2228** [creativetimofficial/light-bootstrap-dashboard-react#6]
hi,

When i tried to perform npm start, it gives me the below error and the site is not rendering

Compiled with warnings.

./~/source-map/lib/source-map/source-map-generator.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./~/source-map/lib/source-map/source-map-consumer.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./~/source-map/lib/source-map/source-node.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

I tried upgrading webpack, react-scripts and even source-map. NOthing worked out 

Please help me how to resolve this issue

**Comment by EINazare** [comment]
Hello @guru2228 . 

We've done dome testing and we didn't get those warnings. Can you please tell us what nodeJs and npm versions do you have, or can you make sure you have the latest npm and nodeJs versions?
From what we've found, the problem should be [here](https://github.com/facebookincubator/create-react-app/pull/2243/commits/5e06c6e5612a27c83b98846ec82e12a06cef3304) . You should make those changes.
But i would recommend you install the latest nodeJs and npm, delete node_modules from your app, and install it again with `npm install` .

Best, Manu.

**Comment by kershnerd** [comment]
I also have these errors when running npm start.  I am on Windows 10 with the node version 8.9.3 and npm version 5.6.0.

The changes you mention in the link have already been applied so nothing to do there.  Any other suggestions?

**Comment by kershnerd** [comment]
I was able to fix this by upgrading the react-scripts in the package.json from 1.0.10 to 1.0.17.

@guru2228 can you confirm this fixed your issue as well?
