### ISSUE TITLE
[Bug] fail to strart server

### ISSUE THREAD

**Issue by tramphbHQ2-GE07** [creativetimofficial/light-bootstrap-dashboard-react#60]
### Version
1.3.0
### Reproduction link
https://demos.creative-tim.com/light-bootstrap-dashboard-react/#/admin/dashboard
### Operating System
windows 10
### Device
PC
### Browser & Version
chorme version 77.0
### Steps to reproduce
I using npm start to start server but always appear error: "Can't resolve 'layouts/Admin.jsx' in 'C:\Users\xxx\Documents\Project\react\src'"
### What is expected?
fix error
### What is actually happening?
npm not start

---

**Comment by EINazare** [comment]
Hello there, @tramphbHQ2-GE07 ,

[Please read this thread here.](https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/4)

Best,
Manu
