### ISSUE TITLE
[Documentation Broken] Some on the links on the free documentation are broken

### ISSUE THREAD

**Issue by GitHubTodoOpen** [creativetimofficial/light-bootstrap-dashboard-react#63]
Got this on the console, the page diasplays blanc on the doc link:
https://demos.creative-tim.com/light-bootstrap-dashboard-react/#/documentation/inputs
<img width="1677" alt="Screen Shot 2020-01-22 at 7 43 37 AM" src="https://user-images.githubusercontent.com/31350366/72891778-66544000-3ceb-11ea-9628-29de54181f0b.png">

**Comment by EINazare** [comment]
Hello there, @GitHubTodoOpen ,

Thank you for your interest in working with our products.
I just made a quick change. It seems that we were using some props badly on that page.
Everything should work just fine now.

Best,
Manu
