### ISSUE TITLE
Form drop down

### ISSUE THREAD

**Issue by a35096** [creativetimofficial/light-bootstrap-dashboard-react#65]
Hello i'm not sure if im in the right place, but how can I use the select input in the forms? I look in the react-boostrap and I tried to use the 'option' and 'select' in the type but is not working.

**Comment by EINazare** [comment]
Hello there, @a35096 ,

Here is a sample code for your need:
```
  <FormGroup>
    <ControlLabel>Hey</ControlLabel>
    <FormControl componentClass="select">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </FormControl>
  </FormGroup>
```

Best,
Manu
