### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by trix0** [creativetimofficial/light-bootstrap-dashboard-react#7]
Hey i cloned->npm install -> npm start and I got this error :) any idea how to fix this ?

Log:https://gist.github.com/trix0/ad6a312b242920c1d303bf226fd62321

**Comment by EINazare** [comment]
Hello @trix0 ,

And thank you for your interest in our products.
Have you installed [node_modules](https://nodejs.org/en/)? It has to be installed globally.
I've seen something in your link there. Are you using Linux?
This [this is a tutorial](https://www.youtube.com/watch?v=73Sml-miP00) on how to install node js with npm on an ubuntu machine.

Best, 
Manu

**Comment by trix0** [comment]
Globally ? I ll give it a shot

On Jan 26, 2018 07:42, "Nazare Emanuel-Ioan" <notifications@github.com>
wrote:

Hello @trix0 <https://github.com/trix0> ,

And thank you for your interest in our products.
Have you installed node_modules <https://nodejs.org/en/>? It has to be
installed globally.
I've seen something in your link there. Are you using Linux?
This this is a tutorial <https://www.youtube.com/watch?v=73Sml-miP00> on
how to install node js with npm on an ubuntu machine.

Best,
Manu

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/creativetimofficial/light-bootstrap-dashboard-react/issues/7#issuecomment-360697461>,
or mute the thread
