### ISSUE TITLE
[Question] Injecting Rows and Columns on the fly?

### ISSUE THREAD

**Issue by cthae** [creativetimofficial/light-bootstrap-dashboard-react#71]
### What is your enhancement?
I'm using this boilerplate in conjunction with websocket as a dashboard for various backend scripts. Sometimes I want to inject results in DOM. I can do that using conventional methods, ofcourse. But it would have been so much more confortable to keep using the concepts of <Row> and <Col> for it.

I wonder if it's possible and if it is, then a few examples wouldn't harm in the documentation.

**Comment by EINazare** [comment]
Hello there, @cthae ,

Unfortunately, I do not know how to help you in this matter.
I Will leave the issue open for 30 days, and if no one will be able to help you, I will close it.

Best,
Manu
