### ISSUE TITLE
Notification problem

### ISSUE THREAD

**Issue by mohamed0group** [creativetimofficial/light-bootstrap-dashboard-react#8]
Notification does not show up correctly on small screens 

![screenshot-2018-2-9 light bootstrap dashboard - react](https://user-images.githubusercontent.com/34784505/36053930-ddfad208-0e04-11e8-8d29-86409f4d7533.png)

**Comment by EINazare** [comment]
Hello @mohamed0group ,

The Notifications actually work correctly. The thing is that if you open the dashboard in a small screen for start than it will render correctly. If you open the dashboard on a larger screen and than open the responsive mode the notifications won't rerender and will stay like that (like on a bigger screen).
Please take a look inside of the archive i've uploaded. You will understand better what happens.

Best,
Manu
[Archive.zip](https://github.com/creativetimofficial/light-bootstrap-dashboard-react/files/1715544/Archive.zip)

**Comment by lacymorrow** [comment]
FWIW I believe that is unexpected behavior.

**Comment by mohamed0group** [comment]
I understand now. I have seen this behavior before and it always happens with fixed position elements. And it is no longer an issue since it will show up correctly in small screen. Thanks @EINazare
