### ISSUE TITLE
Page container is wider than the viewport

### ISSUE THREAD

**Issue by lacymorrow** [creativetimofficial/light-bootstrap-dashboard-react#9]
Great work on this project, there are a few places where it is not completely responsive. The footer flows out of it's container and breaks the page flow.
![screen shot 2018-02-12 at 10 45 52 am](https://user-images.githubusercontent.com/1311301/36113589-2a450be0-0fe2-11e8-8c95-c4826b9ccfd1.png)

**Comment by EINazare** [comment]
Hello @lacymorrow ,

Thank you for your interest in our product.
To fix this, you only have to make the container of the footer fluid.

Best,
Manu
